# Generated by Django 4.0.4 on 2022-08-11 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_library_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='total_orders',
            field=models.IntegerField(default=0),
        ),
    ]
