# Generated by Django 4.0.4 on 2022-10-24 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_userprofile_total_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='total_orders',
        ),
    ]
