# Generated by Django 4.0.4 on 2022-08-11 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presets', '0003_alter_review_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='preset',
            name='rateing',
            field=models.IntegerField(default=0),
        ),
    ]
