# Generated by Django 4.0.4 on 2022-08-11 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presets', '0004_preset_rateing'),
    ]

    operations = [
        migrations.AddField(
            model_name='preset',
            name='clicks',
            field=models.IntegerField(default=0),
        ),
    ]
