# Generated by Django 4.0.4 on 2022-08-11 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presets', '0005_preset_clicks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=30)),
            ],
        ),
    ]
