# Generated by Django 4.0.4 on 2022-08-11 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presets', '0006_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='preset',
            name='tags',
            field=models.ManyToManyField(to='presets.tags'),
        ),
    ]
